# This docker-compose.yml file will bring up panhandler on an unreachable backend network, as well 
# as a NGINX proxy server that will allow access to panhandler via TLS

version: '3.4'

services:
  panhandler:
    image: paloaltonetworks/panhandler:latest
    # Change image tag from "latest" to "dev" to switch branches.
    # When switching between dev and latest clear the cache with:
    # https://panhandler:4433/clear_cache
    container_name: panhandler
    restart: on-failure
    environment:
      - CNC_USERNAME=tobias
      - CNC_PASSWORD=panme
    volumes:
      - "user-dir:/home/cnc_user"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - ph-backend

  nginx:
   image: nginx
   container_name: nginx
   restart: on-failure
   ports:
    - "4433:443"
   volumes:
     - "./conf.d:/etc/nginx/conf.d"
   networks:
    - ph-frontend
    - ph-backend   


volumes:
  user-dir:
  nginx:

networks:
  ph-backend:
  ph-frontend:
